import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { LanguageProvider } from "@/components/LanguageProvider";
import TopBar from "@/components/TopBar";
import FontWrapper from "./FontWrapper";
import { Noto_Naskh_Arabic } from 'next/font/google';

const notoArabic = Noto_Naskh_Arabic({
  subsets: ['arabic'],
  weight: ['400'],
  variable: '--font-arabic',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LanguageProvider>
          {/* Apply Arabic font globally if Arabic is selected */}
          <FontWrapper>
            <TopBar />
            <main className="flex-1 flex flex-col">
              {children}
            </main>
          </FontWrapper>
        </LanguageProvider>
      </body>
    </html>
  );
}
